// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBioj8_a08oWsNvzmv_12vKvoB8nLJaIxQ',
    appId: '1:389470119850:web:16d26da2f7686b04842dd3',
    messagingSenderId: '389470119850',
    projectId: 'wigiv-e47c2',
    authDomain: 'wigiv-e47c2.firebaseapp.com',
    databaseURL: 'https://wigiv-e47c2.firebaseio.com',
    storageBucket: 'wigiv-e47c2.firebasestorage.app',
    measurementId: 'G-HR19HCTM78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8PUxXafGtMrd9_ZxHgMfOASxdQxEwUE',
    appId: '1:389470119850:android:7d6d7a6e1682dc30842dd3',
    messagingSenderId: '389470119850',
    projectId: 'wigiv-e47c2',
    databaseURL: 'https://wigiv-e47c2.firebaseio.com',
    storageBucket: 'wigiv-e47c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolomRcf-HYCwf-XaqHIGHpDXVitwTQE4',
    appId: '1:389470119850:ios:77f7176fc35b13a0842dd3',
    messagingSenderId: '389470119850',
    projectId: 'wigiv-e47c2',
    databaseURL: 'https://wigiv-e47c2.firebaseio.com',
    storageBucket: 'wigiv-e47c2.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolomRcf-HYCwf-XaqHIGHpDXVitwTQE4',
    appId: '1:389470119850:ios:77f7176fc35b13a0842dd3',
    messagingSenderId: '389470119850',
    projectId: 'wigiv-e47c2',
    databaseURL: 'https://wigiv-e47c2.firebaseio.com',
    storageBucket: 'wigiv-e47c2.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBioj8_a08oWsNvzmv_12vKvoB8nLJaIxQ',
    appId: '1:389470119850:web:d3a15a61b47d6c0f842dd3',
    messagingSenderId: '389470119850',
    projectId: 'wigiv-e47c2',
    authDomain: 'wigiv-e47c2.firebaseapp.com',
    databaseURL: 'https://wigiv-e47c2.firebaseio.com',
    storageBucket: 'wigiv-e47c2.firebasestorage.app',
    measurementId: 'G-7W9442CWWK',
  );
}
